services:
  postgres:
    image: postgres:bookworm
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:4173"
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  db_data:
