services:
  postgres:
    image: postgres:bookworm
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" 
  
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    env_file:
      - .env 
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  db_data:
