services:
  postgres:
    image: postgres:bookworm
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    env_file:
      - .env 
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - postgres
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:4173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend

volumes:
  db_data:
