FROM python:3.13-alpine

# Create a directory for the app
WORKDIR /app

# Add everything in the current directory to the app directory 
ADD . /app

# Install uv
RUN pip install uv 
RUN uv sync

# Run the app
CMD ["uv", "run", "server", "0.0.0.0", "8000", "2"]

