// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, urlSearchParamsBodySerializer } from '@hey-api/client-fetch';
import type { CheckTokenLoginGetData, CheckTokenLoginGetResponse, LoginForTokenLoginPostData, LoginForTokenLoginPostResponse, LoginForTokenLoginPostError, CreateUserUserPostData, CreateUserUserPostResponse, CreateUserUserPostError, SendVerificationEmailUserVerifyEmailPostData, VerifyUserUserVerifyGetData, VerifyUserUserVerifyGetError, DeleteMeUserMeDeleteData, GetMeUserMeGetData, GetMeUserMeGetResponse, UpdateMeUserMePutData, UpdateMeUserMePutResponse, UpdateMeUserMePutError, UpdateEmailUsermeEmailGetData, UpdateEmailUsermeEmailGetError, GetActivitiesActivityGetData, GetActivitiesActivityGetResponse, GetActivitiesActivityGetError, CreateActivityActivityPostData, CreateActivityActivityPostResponse, CreateActivityActivityPostError, DeleteActivityActivityActivityIdDeleteData, DeleteActivityActivityActivityIdDeleteResponse, DeleteActivityActivityActivityIdDeleteError, GetShapesShapeGetData, GetShapesShapeGetResponse, GetShapesShapeGetError, CreateShapeShapePostData, CreateShapeShapePostResponse, CreateShapeShapePostError, GetCurrentShapeShapeCurrentGetData, GetCurrentShapeShapeCurrentGetResponse, DeleteShapeShapeShapeIdDeleteData, DeleteShapeShapeShapeIdDeleteResponse, DeleteShapeShapeShapeIdDeleteError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Check Token
 * Check if the provided token is valid.
 *
 * This function is an endpoint.
 *
 * Args:
 * token (str): The access token to check, automatically injected by FastAPI.
 * Returns:
 * dict[str, str]: A dictionary containing the token if valid.
 */
export const checkTokenLoginGet = <ThrowOnError extends boolean = false>(options?: Options<CheckTokenLoginGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<CheckTokenLoginGetResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/login/',
        ...options
    });
};

/**
 * Login For Token
 * Login endpoint to authenticate user and generate access token.
 *
 * This function is an endpoint.
 *
 * Args:
 * form_data (OAuth2PasswordRequestForm): The form data containing username and password, automatically injected by FastAPI.
 * response (Response): The HTTP response object.
 * session (Session): The database session, automatically injected by FastAPI.
 */
export const loginForTokenLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginForTokenLoginPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LoginForTokenLoginPostResponse, LoginForTokenLoginPostError, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/login/',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Create User
 * Create a new user.
 *
 * This function is an endpoint.
 *
 * Args:
 * user (RegisterUser): The user to create.
 * session (Session): The database session, automatically injected by FastAPI.
 * send_email (SendEmailType): The email sending function, automatically injected by FastAPI.
 * Returns:
 * UserBase: The created user with basic details.
 */
export const createUserUserPost = <ThrowOnError extends boolean = false>(options: Options<CreateUserUserPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateUserUserPostResponse, CreateUserUserPostError, ThrowOnError>({
        url: '/user/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Send Verification Email
 * Send a verification email to the user if they are not verified.
 *
 * This function is an endpoint.
 *
 * Args:
 * user (UserBase): The current user, automatically injected by FastAPI.
 * session (Session): The database session, automatically injected by FastAPI.
 * send_email (SendEmailType): The email sending function, automatically injected by FastAPI.
 * Returns:
 * Response: A response indicating the email has been sent.
 */
export const sendVerificationEmailUserVerifyEmailPost = <ThrowOnError extends boolean = false>(options?: Options<SendVerificationEmailUserVerifyEmailPostData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/verify-email',
        ...options
    });
};

/**
 * Verify User
 * Verify a user using the verification code from the token.
 *
 * This function is an endpoint.
 *
 * Args:
 * token(dict[str, Any]): The token containing the verification code, automatically injected by FastAPI.
 * session (Session): The database session, automatically injected by FastAPI.
 * Returns:
 * Response: A response indicating the user has been verified.
 */
export const verifyUserUserVerifyGet = <ThrowOnError extends boolean = false>(options: Options<VerifyUserUserVerifyGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, VerifyUserUserVerifyGetError, ThrowOnError>({
        url: '/user/verify',
        ...options
    });
};

/**
 * Delete Me
 * Delete the current user.
 *
 * This function is an endpoint.
 *
 * Args:
 * user (UserBase): The current user, automatically injected by FastAPI.
 * session (Session): The database session, automatically injected by FastAPI.
 * Returns:
 * Response: An ok response indicating the user has been deleted.
 */
export const deleteMeUserMeDelete = <ThrowOnError extends boolean = false>(options?: Options<DeleteMeUserMeDeleteData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).delete<unknown, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/me',
        ...options
    });
};

/**
 * Get Me
 * Get the current user's details.
 *
 * This function is an endpoint.
 *
 * Args:
 * user (UserBase): The current user, automatically injected by FastAPI.
 * Returns:
 * UserBase: The current user's details.
 */
export const getMeUserMeGet = <ThrowOnError extends boolean = false>(options?: Options<GetMeUserMeGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMeUserMeGetResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/me',
        ...options
    });
};

/**
 * Update Me
 * Update the current user's details.
 *
 * This function is an endpoint.
 *
 * Args:
 * modifications (ModifyUser): The modifications to apply to the user.
 * user (UserBase): The current user, automatically injected by FastAPI.
 * session (Session): The database session, automatically injected by FastAPI.
 * send_email (SendEmailType): The email sending function, automatically injected by FastAPI.
 * Returns:
 * UserBase: The updated user with basic details.
 */
export const updateMeUserMePut = <ThrowOnError extends boolean = false>(options: Options<UpdateMeUserMePutData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UpdateMeUserMePutResponse, UpdateMeUserMePutError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/me',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Update Email
 * Update the current user's email using a verification token.
 *
 * This function is an endpoint.
 *
 * Args:
 * token (str): The verification token to update the email.
 * session (Session): The database session, automatically injected by FastAPI.
 * Returns:
 * str: The new email of the user.
 */
export const updateEmailUsermeEmailGet = <ThrowOnError extends boolean = false>(options: Options<UpdateEmailUsermeEmailGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, UpdateEmailUsermeEmailGetError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/userme/email',
        ...options
    });
};

/**
 * Get Activities
 * Get all activities for the user within a date range and optional minigame filter.
 *
 * This function is an endpoint.
 *
 * Args:
 * user (UserBase): The current user, automatically injected by FastAPI.
 * minigame_filter (str | None): The minigame filter (optional).
 * from_date (str | None): The start date in ISO format (optional).
 * to_date (str | None): The end date in ISO format (optional).
 * session (Session): The database session, automatically injected by FastAPI.
 * Returns:
 * list[ActivityUUID]: A list of activities for the user within the specified date range and filter.
 */
export const getActivitiesActivityGet = <ThrowOnError extends boolean = false>(options?: Options<GetActivitiesActivityGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetActivitiesActivityGetResponse, GetActivitiesActivityGetError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/activity/',
        ...options
    });
};

/**
 * Create Activity
 * Create a new activity for the user.
 *
 * This function is an endpoint.
 *
 * Args:
 * activity (ActivityBase): The activity data to create.
 * user (UserBase): The current user, automatically injected by FastAPI.
 * session (Session): The database session, automatically injected by FastAPI.
 * Returns:
 * ActivityFull: The created activity with full details.
 */
export const createActivityActivityPost = <ThrowOnError extends boolean = false>(options: Options<CreateActivityActivityPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateActivityActivityPostResponse, CreateActivityActivityPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/activity/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete Activity
 * Delete an activity by its ID.
 *
 * This function is an endpoint.
 *
 * Args:
 * activity_id (int): The ID of the activity to delete.
 * user (UserBase): The current user, automatically injected by FastAPI.
 * session (Session): The database session, automatically injected by FastAPI.
 * Returns:
 * ActivityBase: The deleted activity details.
 */
export const deleteActivityActivityActivityIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteActivityActivityActivityIdDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteActivityActivityActivityIdDeleteResponse, DeleteActivityActivityActivityIdDeleteError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/activity/{activity_id}',
        ...options
    });
};

/**
 * Get Shapes
 * Get all shapes for the user within a date range.
 *
 * This function is an endpoint.
 *
 * Args:
 * user (UserBase): The current user, automatically injected by FastAPI.
 * from_date (str | None): The start date in ISO format (optional).
 * to_date (str | None): The end date in ISO format (optional).
 * session (Session): The database session, automatically injected by FastAPI.
 *
 * Returns:
 * list[ShapeFull]: A list of shapes for the user within the specified date range.
 */
export const getShapesShapeGet = <ThrowOnError extends boolean = false>(options?: Options<GetShapesShapeGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetShapesShapeGetResponse, GetShapesShapeGetError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/shape/',
        ...options
    });
};

/**
 * Create Shape
 * Create a new shape for the user.
 *
 * This function is an endpoint.
 *
 * Args:
 * shape (ShapeBase): The shape data to create.
 * user (UserBase): The current user, automatically injected by FastAPI.
 * session (Session): The database session, automatically injected by FastAPI.
 * Returns:
 * ShapeFull: The created shape with full details.
 */
export const createShapeShapePost = <ThrowOnError extends boolean = false>(options: Options<CreateShapeShapePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateShapeShapePostResponse, CreateShapeShapePostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/shape/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Current Shape
 * Get the current shape for the user.
 *
 * This function is an endpoint.
 *
 * Args:
 * user (UserBase): The current user, automatically injected by FastAPI.
 * session (Session): The database session, automatically injected by FastAPI.
 * Returns:
 * ShapeFull: The current shape for the user.
 */
export const getCurrentShapeShapeCurrentGet = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentShapeShapeCurrentGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCurrentShapeShapeCurrentGetResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/shape/current',
        ...options
    });
};

/**
 * Delete Shape
 * Delete a shape by its ID.
 *
 * This function is an endpoint.
 *
 * Args:
 * shape_id (int): The ID of the shape to delete.
 * user (UserBase): The current user, automatically injected by FastAPI.
 * session (Session): The database session, automatically injected by FastAPI.
 * Returns:
 * ShapeBase: The deleted shape data.
 */
export const deleteShapeShapeShapeIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteShapeShapeShapeIdDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteShapeShapeShapeIdDeleteResponse, DeleteShapeShapeShapeIdDeleteError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/shape/{shape_id}',
        ...options
    });
};