// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, urlSearchParamsBodySerializer } from '@hey-api/client-fetch';
import type { CheckTokenLoginGetData, CheckTokenLoginGetResponse, LoginForTokenLoginPostData, LoginForTokenLoginPostResponse, LoginForTokenLoginPostError, RefreshTokenLoginRefreshPostData, RefreshTokenLoginRefreshPostResponse, CreateUserUserPostData, CreateUserUserPostResponse, CreateUserUserPostError, VerifyUserUserVerifyVerificationCodePostData, VerifyUserUserVerifyVerificationCodePostError, DeleteMeUserMeDeleteData, GetMeUserMeGetData, GetMeUserMeGetResponse, UpdateMeUserMePutData, UpdateMeUserMePutResponse, UpdateMeUserMePutError, GetActivitiesActivityGetData, GetActivitiesActivityGetResponse, GetActivitiesActivityGetError, CreateActivityActivityPostData, CreateActivityActivityPostResponse, CreateActivityActivityPostError, DeleteActivityActivityActivityIdDeleteData, DeleteActivityActivityActivityIdDeleteResponse, DeleteActivityActivityActivityIdDeleteError, GetShapesShapeGetData, GetShapesShapeGetResponse, GetShapesShapeGetError, CreateShapeShapePostData, CreateShapeShapePostResponse, CreateShapeShapePostError, DeleteShapeShapeShapeIdDeleteData, DeleteShapeShapeShapeIdDeleteResponse, DeleteShapeShapeShapeIdDeleteError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Check Token
 */
export const checkTokenLoginGet = <ThrowOnError extends boolean = false>(options?: Options<CheckTokenLoginGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<CheckTokenLoginGetResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/login/',
        ...options
    });
};

/**
 * Login For Token
 */
export const loginForTokenLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginForTokenLoginPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LoginForTokenLoginPostResponse, LoginForTokenLoginPostError, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/login/',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Refresh Token
 */
export const refreshTokenLoginRefreshPost = <ThrowOnError extends boolean = false>(options?: Options<RefreshTokenLoginRefreshPostData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<RefreshTokenLoginRefreshPostResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/login/refresh',
        ...options
    });
};

/**
 * Create User
 */
export const createUserUserPost = <ThrowOnError extends boolean = false>(options: Options<CreateUserUserPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateUserUserPostResponse, CreateUserUserPostError, ThrowOnError>({
        url: '/user/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Verify User
 */
export const verifyUserUserVerifyVerificationCodePost = <ThrowOnError extends boolean = false>(options: Options<VerifyUserUserVerifyVerificationCodePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, VerifyUserUserVerifyVerificationCodePostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/verify/{verification_code}',
        ...options
    });
};

/**
 * Delete Me
 */
export const deleteMeUserMeDelete = <ThrowOnError extends boolean = false>(options?: Options<DeleteMeUserMeDeleteData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).delete<unknown, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/me',
        ...options
    });
};

/**
 * Get Me
 */
export const getMeUserMeGet = <ThrowOnError extends boolean = false>(options?: Options<GetMeUserMeGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMeUserMeGetResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/me',
        ...options
    });
};

/**
 * Update Me
 */
export const updateMeUserMePut = <ThrowOnError extends boolean = false>(options: Options<UpdateMeUserMePutData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UpdateMeUserMePutResponse, UpdateMeUserMePutError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/me',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Activities
 */
export const getActivitiesActivityGet = <ThrowOnError extends boolean = false>(options?: Options<GetActivitiesActivityGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetActivitiesActivityGetResponse, GetActivitiesActivityGetError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/activity/',
        ...options
    });
};

/**
 * Create Activity
 */
export const createActivityActivityPost = <ThrowOnError extends boolean = false>(options: Options<CreateActivityActivityPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateActivityActivityPostResponse, CreateActivityActivityPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/activity/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete Activity
 */
export const deleteActivityActivityActivityIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteActivityActivityActivityIdDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteActivityActivityActivityIdDeleteResponse, DeleteActivityActivityActivityIdDeleteError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/activity/{activity_id}',
        ...options
    });
};

/**
 * Get Shapes
 */
export const getShapesShapeGet = <ThrowOnError extends boolean = false>(options?: Options<GetShapesShapeGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetShapesShapeGetResponse, GetShapesShapeGetError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/shape/',
        ...options
    });
};

/**
 * Create Shape
 */
export const createShapeShapePost = <ThrowOnError extends boolean = false>(options: Options<CreateShapeShapePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateShapeShapePostResponse, CreateShapeShapePostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/shape/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete Shape
 */
export const deleteShapeShapeShapeIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteShapeShapeShapeIdDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteShapeShapeShapeIdDeleteResponse, DeleteShapeShapeShapeIdDeleteError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/shape/{shape_id}',
        ...options
    });
};