// This file is auto-generated by @hey-api/openapi-ts

/**
 * Base pydantic model for activity data.
 */
export type ActivityBase = {
    date: string;
    minigame: string;
    duration: number;
    score: number;
    activity_points: number;
    extra_data: string;
};

/**
 * Pydantic model for full activity data including user information.
 */
export type ActivityFull = {
    date: string;
    minigame: string;
    duration: number;
    score: number;
    activity_points: number;
    extra_data: string;
    uuid: number;
    user: UserBase;
};

/**
 * Pydantic model for activity data with UUID.
 */
export type ActivityUuid = {
    date: string;
    minigame: string;
    duration: number;
    score: number;
    activity_points: number;
    extra_data: string;
    uuid: number;
};

export type BodyLoginForTokenLoginPost = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Pydantic model for modifying user data.
 */
export type ModifyUser = {
    email?: string | null;
    name?: string | null;
    year_of_birth?: number | null;
};

/**
 * Pydantic model for registering a new user.
 */
export type RegisterUser = {
    email: string;
    password: string;
    name: string;
    year_of_birth: number;
};

/**
 * Base pydantic model for physical shape data.
 */
export type ShapeBase = {
    date: string;
    weight: number;
    height: number;
};

/**
 * Pydantic model for full physical shape data including user information.
 */
export type ShapeFull = {
    date: string;
    weight: number;
    height: number;
    uuid: number;
    user: UserBase;
};

/**
 * Pydantic model for authentication token data.
 */
export type Token = {
    access_token: string;
    token_type: string;
};

/**
 * Base pydantic model for user data.
 */
export type UserBase = {
    email: string;
    verified: boolean;
    name: string;
    year_of_birth: number;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type CheckTokenLoginGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/login/';
};

export type CheckTokenLoginGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type CheckTokenLoginGetResponse = CheckTokenLoginGetResponses[keyof CheckTokenLoginGetResponses];

export type LoginForTokenLoginPostData = {
    body: BodyLoginForTokenLoginPost;
    path?: never;
    query?: never;
    url: '/login/';
};

export type LoginForTokenLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginForTokenLoginPostError = LoginForTokenLoginPostErrors[keyof LoginForTokenLoginPostErrors];

export type LoginForTokenLoginPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginForTokenLoginPostResponse = LoginForTokenLoginPostResponses[keyof LoginForTokenLoginPostResponses];

export type CreateUserUserPostData = {
    body: RegisterUser;
    path?: never;
    query?: never;
    url: '/user/';
};

export type CreateUserUserPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserUserPostError = CreateUserUserPostErrors[keyof CreateUserUserPostErrors];

export type CreateUserUserPostResponses = {
    /**
     * Successful Response
     */
    200: UserBase;
};

export type CreateUserUserPostResponse = CreateUserUserPostResponses[keyof CreateUserUserPostResponses];

export type VerifyEmailTokenUserMeEmailTokenPostData = {
    body?: never;
    path?: never;
    query: {
        token: string;
    };
    url: '/user/me/email-token';
};

export type VerifyEmailTokenUserMeEmailTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyEmailTokenUserMeEmailTokenPostError = VerifyEmailTokenUserMeEmailTokenPostErrors[keyof VerifyEmailTokenUserMeEmailTokenPostErrors];

export type VerifyEmailTokenUserMeEmailTokenPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SendVerificationEmailUserVerifyEmailPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/verify-email';
};

export type SendVerificationEmailUserVerifyEmailPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteMeUserMeDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/me';
};

export type DeleteMeUserMeDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMeUserMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/me';
};

export type GetMeUserMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserBase;
};

export type GetMeUserMeGetResponse = GetMeUserMeGetResponses[keyof GetMeUserMeGetResponses];

export type UpdateMeUserMePutData = {
    body: ModifyUser;
    path?: never;
    query?: never;
    url: '/user/me';
};

export type UpdateMeUserMePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMeUserMePutError = UpdateMeUserMePutErrors[keyof UpdateMeUserMePutErrors];

export type UpdateMeUserMePutResponses = {
    /**
     * Successful Response
     */
    200: UserBase;
};

export type UpdateMeUserMePutResponse = UpdateMeUserMePutResponses[keyof UpdateMeUserMePutResponses];

export type GetActivitiesActivityGetData = {
    body?: never;
    path?: never;
    query?: {
        minigame_filter?: string | null;
        from_date?: string | null;
        to_date?: string | null;
    };
    url: '/activity/';
};

export type GetActivitiesActivityGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetActivitiesActivityGetError = GetActivitiesActivityGetErrors[keyof GetActivitiesActivityGetErrors];

export type GetActivitiesActivityGetResponses = {
    /**
     * Successful Response
     */
    200: Array<ActivityUuid>;
};

export type GetActivitiesActivityGetResponse = GetActivitiesActivityGetResponses[keyof GetActivitiesActivityGetResponses];

export type CreateActivityActivityPostData = {
    body: ActivityBase;
    path?: never;
    query?: never;
    url: '/activity/';
};

export type CreateActivityActivityPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateActivityActivityPostError = CreateActivityActivityPostErrors[keyof CreateActivityActivityPostErrors];

export type CreateActivityActivityPostResponses = {
    /**
     * Successful Response
     */
    200: ActivityFull;
};

export type CreateActivityActivityPostResponse = CreateActivityActivityPostResponses[keyof CreateActivityActivityPostResponses];

export type DeleteActivityActivityActivityIdDeleteData = {
    body?: never;
    path: {
        activity_id: number;
    };
    query?: never;
    url: '/activity/{activity_id}';
};

export type DeleteActivityActivityActivityIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteActivityActivityActivityIdDeleteError = DeleteActivityActivityActivityIdDeleteErrors[keyof DeleteActivityActivityActivityIdDeleteErrors];

export type DeleteActivityActivityActivityIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: ActivityBase;
};

export type DeleteActivityActivityActivityIdDeleteResponse = DeleteActivityActivityActivityIdDeleteResponses[keyof DeleteActivityActivityActivityIdDeleteResponses];

export type GetShapesShapeGetData = {
    body?: never;
    path?: never;
    query?: {
        from_date?: string | null;
        to_date?: string | null;
    };
    url: '/shape/';
};

export type GetShapesShapeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetShapesShapeGetError = GetShapesShapeGetErrors[keyof GetShapesShapeGetErrors];

export type GetShapesShapeGetResponses = {
    /**
     * Successful Response
     */
    200: Array<ShapeFull>;
};

export type GetShapesShapeGetResponse = GetShapesShapeGetResponses[keyof GetShapesShapeGetResponses];

export type CreateShapeShapePostData = {
    body: ShapeBase;
    path?: never;
    query?: never;
    url: '/shape/';
};

export type CreateShapeShapePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateShapeShapePostError = CreateShapeShapePostErrors[keyof CreateShapeShapePostErrors];

export type CreateShapeShapePostResponses = {
    /**
     * Successful Response
     */
    200: ShapeFull;
};

export type CreateShapeShapePostResponse = CreateShapeShapePostResponses[keyof CreateShapeShapePostResponses];

export type GetCurrentShapeShapeCurrentGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/shape/current';
};

export type GetCurrentShapeShapeCurrentGetResponses = {
    /**
     * Successful Response
     */
    200: ShapeFull;
};

export type GetCurrentShapeShapeCurrentGetResponse = GetCurrentShapeShapeCurrentGetResponses[keyof GetCurrentShapeShapeCurrentGetResponses];

export type DeleteShapeShapeShapeIdDeleteData = {
    body?: never;
    path: {
        shape_id: number;
    };
    query?: never;
    url: '/shape/{shape_id}';
};

export type DeleteShapeShapeShapeIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteShapeShapeShapeIdDeleteError = DeleteShapeShapeShapeIdDeleteErrors[keyof DeleteShapeShapeShapeIdDeleteErrors];

export type DeleteShapeShapeShapeIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: ShapeBase;
};

export type DeleteShapeShapeShapeIdDeleteResponse = DeleteShapeShapeShapeIdDeleteResponses[keyof DeleteShapeShapeShapeIdDeleteResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};