hide footbox
skinparam roundCorner 0
autoactivate on
!theme plain

hide unlinked

' Participantes usuarios
actor "Usuario sin autenticar" as Anon
actor "Usuario autenticado" as Auth
actor "Usuario verificado" as Verified
actor "Sistema" as System


' Clases de React
participant "LoginForm" as LF <<Component>> #LightGreen

participant "Dashboard" as Dashboard <<Component>> #LightGreen
participant "My" as My <<Component>> #LightGreen
participant "CSC" as CSC <<Component>> #LightGreen
participant "Media" as Media <<Component>> #LightGreen
participant "UserStats" as US <<Component>> #LightGreen
participant "UserData" as UserData <<Component>> #LightGreen
participant "DataForm" as DataForm <<Component>> #LightGreen

participant "ApiClient" as ApiClient #LightGreen

' Unity
participant "RINLBody" as RINLBody #BUSINESS
participant "JSConnector" as JSConnector #BUSINESS
participant "GameController" as GameController #BUSINESS
participant "SceneScript" as SceneScript #BUSINESS

' Clases del backend
participant "AuthRouter" as AuthR <<Router>> #LightBlue
participant "ActivityRouter" as ActivityR <<Router>> #LightBlue
participant "ShapeRouter" as ShapeR <<Router>> #LightBlue
participant "UserRouter" as UserR <<Router>> #LightBlue

participant "AuthDAO" as AuthDAO #LightCyan
participant "ActivityDAO" as ActivityDAO #LightCyan
participant "ShapeDAO" as ShapeDAO #LightCyan
participant "UserDAO" as UserDAO #LightCyan

participant "ActivitySchema" as ActivitySchema #LightSteelBlue
participant "ShapeSchema" as ShapeSchema #LightSteelBlue
participant "UserSchema" as UserSchema #LightSteelBlue
participant "TokenSchema" as AuthSchema #LightSteelBlue

' ' Clases de modelos
' create "User" as UserEntity %lighten("#IndianRed", 20)
' create "Activity" as ActivityEntity %lighten("#IndianRed", 20)
' create "Shape" as ShapeEntity %lighten("#IndianRed", 20)

