@startuml AbrirJuego

!include common.puml
autoactivate off

Verified -> Media ++ : El usuario abre la página del\njuego desde el menú principal

create PoseLandmarker as PL #LightGreen
Media -> PL ++ : createPoseLandmarker(capacidadDelModelo)

create UnityClient as UC #LightGreen
Media -> UC ++ : useUnityClient()

participant "JSConnector" as JSConnector #BUSINESS

' Enviar información a Unity
Media -> UC : sendUserData(data)
activate JSConnector
UC ->> JSConnector : sendUnityMessage("JSConnector", "SetVideoSize", videoSize)
JSConnector -> JSConnector : setVideoSize(videoSize)
JSConnector -->> UC : sendAck("SetVideoSize")

UC ->> JSConnector: sendUnityMessage("JSConnector", "SetCurrentShape", shape)
JSConnector -> JSConnector : setCurrentShape(shape)
JSConnector -->> UC : sendAck("SetCurrentShape")

UC ->> JSConnector: sendUnityMessage("JSConnector", "SetCurrentUser", user)
JSConnector -> JSConnector : setCurrentUser(user)
JSConnector -->> UC : sendAck("SetCurrentUser")

UC --> Media --: ok

Media -> Verified -- : Muestra la pantalla del juego

@enduml
