@startuml CalibrarCamara

!include common.puml
autoactivate off

activate RINLBody
activate SceneScript

||10|
ref over Verified, RINLBody : Detectar postura

||10|
SceneScript -> Verified : Se muestran las instrucciones\nde calibración

||10|
loop Hasta que la cámara esté calibrada
    ||10|
    ref over Verified, RINLBody : Detectar postura
    RINLBody ->> SceneScript : Calibración
end

@enduml