@startuml EscogerMinijuego

!include common.puml
autoactivate off

activate RINLBody
ref over RINLBody : Detectar postura

RINLBody ->> SceneScript ++ : El usuario posiciona una de sus manos\nsobre un botón de minijuego
SceneScript -->> Verified : Muestra un círculo creciente en la mano

alt El usuario no mueve la mano
    ...2 segundos después...
    SceneScript -> SceneScript : Se selecciona el minijuego escogido.

    ref over Verified, RINLBody, SceneScript : Escoger dificultad

else El usuario mueve la mano
    SceneScript -->> Verified : Se oculta el círculo creciente

end

@enduml