@startuml EscogerDificultad

!include common.puml
autoactivate off

activate RINLBody
ref over RINLBody : Detectar postura

RINLBody ->> SceneScript ++ : El usuario posiciona una de sus manos\nsobre un botón de dificultad
SceneScript -->> Verified : Mustra la información de la dificultad
SceneScript -->> Verified : Muestra un círculo creciente en la mano

alt El usuario no mueve la mano
    ...2 segundos después...
    SceneScript -> SceneScript : Se selecciona la dificultad escogida.

    ref over Verified, RINLBody, SceneScript : Jugar minijuego globos / Jugar minijuego esquivar

else El usuario mueve la mano
    SceneScript -->> Verified : Se oculta el círculo creciente

end

@enduml