@startuml JugarGlobos

!include common.puml

autoactivate off

activate RINLBody
||5|
ref over Verified, RINLBody : Detectar postura

RINLBody -> SceneScript ++ : El usuario comienza el videojuego

loop Hasta que se agote el tiempo
    SceneScript -->> Verified : Muestra un globo para que el usuario lo explote
    RINLBody ->> SceneScript : Explota el globo tocándolo con la mano
end

ref over Verified, RINLBody, SceneScript : Ver puntuaciones

@enduml