@startuml PantallaCompleta

!include common.puml

participant UnityClient as UC #LightGreen

Verified -> Media : El usuario hace click en el botón de pantalla completa
Media -> UC : requestFullscreen()
return
return La página presenta el juego en pantalla completa

@enduml