startuml

!include common.puml
' participant "User" as UserEntity %lighten("#IndianRed", 20)
' create "Activity" as ActivityEntity %lighten("#IndianRed", 20)
' create "Shape" as ShapeEntity %lighten("#IndianRed", 20)

@enduml