@startuml Registrarse

!include common.puml

Anon -> LF : Solicita registrarse
autoactivate off
LF --> Anon : Muestra formulario de registro

Anon -> LF : Completa formulario de registro
autoactivate on
LF -> ApiClient : createUserUserPost(userData)
ApiClient -> UserR : POST /user
UserR -> UserDAO : create_user(userData: UserSchema)

alt El usuario no existe
    create "User" as UserEntity %lighten("#IndianRed", 20)

    autoactivate off
    UserDAO -> UserEntity : create(userData)

    UserDAO --> UserR : UserSchema

    ref over UserR, UserDAO : Mandar correo de verificación

    UserR --> ApiClient : 200 Created
    ApiClient --> LF : ok

    ref over Anon, LF : Iniciar sesión

else El usuario ya existe
    autoactivate on
    UserDAO --> UserR : HTTPException
    UserR --> ApiClient : 400 User already exists
    ApiClient --> LF : User already exists
    LF --> Anon : Muestra error de usuario ya existente
end

@enduml
