@startuml Registrarse

!include common.puml

' autonumber 1.1
Anon -> LF : Solicita registrarse
LF --> Anon : Muestra formulario de registro

' autonumber 2.1
Anon -> LF : Completa formulario de registro
' autonumber 2.1.1
LF -> ApiClient : createUserUserPost(userData)
' autonumber 2.1.1
ApiClient -> UserR : POST /user
' autonumber 2.1.1.1
UserR -> UserDAO : create_user(userData: UserSchema)

alt El usuario no existe
    create entity "User" as UserEntity %lighten("#IndianRed", 20)
    UserDAO -> UserEntity : create(userData)
    UserDAO --> UserR : UserSchema

    UserR --> ApiClient : 200 Created
    ApiClient --> LF : ok

    ref over Anon, LF : Iniciar sesión

else El usuario ya existe
    UserDAO --> UserR : HTTPException
    UserR --> ApiClient : 400 User already exists
    ApiClient --> LF : User already exists
    LF -> Anon : Muestra error de usuario ya existente
end

@enduml
