@startuml VerDatosPersonales

!include common.puml
participant "User" as UserEntity %lighten("#IndianRed", 20)

Auth -> UserData : Entra en la página de datos personales
UserData -> ApiClient : get_user_data()
ApiClient -> UserR : GET /user
UserR -> UserDAO : get_user(email)
UserDAO -> UserEntity : query(email)
UserEntity --> UserDAO : UserEntity
UserDAO --> UserR : UserSchema
UserR --> ApiClient : userData
ApiClient --> UserData : userData
UserData --> Auth : Muestra los datos personales

@enduml