@startuml "casosuso"

:Sistema: as sys
:Usuario sin autenticar: as anon
:Usuario autenticado: as userauth
:Usuario verificado: as userverif 

left to right direction
package "Gestión de usuario" {
    usecase Registrarse as "UC-0001\nRegistrarse"
    usecase IniciarSesion as "UC-0002\nIniciar sesión
    ---
    Extensiones:
    Registrarse"
    usecase MandarCorreoVerificacion as "UC-0003\nMandar correo de verificación"
    usecase CerrarSesion as "UC-0006\nCerrar sesión"
    usecase VerDatosPersonales as "UC-0004\nVer datos personales
    ---
    Extensiones:
    Eliminar cuenta
    Cerrar sesión
    Verificar correo electrónico
    Modificar datos personales
    Añadir forma física"
    usecase EliminarCuenta as "UC-0005\nEliminar cuenta"
    usecase VerificarCorreoElectronico as "UC-0007\nVerificar correo electrónico"
    usecase ModificarDatosPersonales as "UC-0008\nModificar datos personales"
}

package "Estadísticas y seguimiento" {
    usecase AnadirFormaFisica as "UC-0009\nAñadir forma física"
    usecase ConsultarEstadisticas as "UC-0010\nConsultar estadísticas
    ---
    Extensiones:
    Filtrar estadísticas"
    usecase FiltrarEstadisticas as "UC-0011\nFiltrar estadísticas"
}

package "Juego" {
    usecase AbrirJuego as "
    UC-0012
    Abrir el juego
    ---
    Extensiones:
    Activar pantalla completa
    Calibrar cámara
    Escoger minijuego
    "
    usecase PantallaCompleta as "UC-0013\nActivar pantalla completa"
    usecase Calibrar as "UC-0014\nCalibrar cámara"
    usecase EscogerMinijuego as "
    UC-0015
    Escoger minijuego
    ---
    Extensiones:
    Escoger dificultad
    "
    usecase EscogerDificultad as "
    UC-0016
    Escoger dificultad
    ---
    Extensiones:
    Jugar minijuego globos
    Jugar minijuego esquivar
    "
    usecase JugarGlobos as "
    UC-0017
    Jugar minijuego globos
    ---
    Extensiones:
    Ver puntuaciones"
    usecase JugarEsquivar as "
    UC-0018
    Jugar minijuego esquivar
    ---
    Extensiones:
    Ver puntuaciones
    "
    usecase Puntuacion as "
    UC-0019
    Ver puntuaciones
    ---
    Extensiones:
    Volver a jugar
    Volver al menú principal
    "
    usecase VolverJugar as "
    UC-0020
    Volver a jugar
    ---
    Extensiones:
    Escoger dificultad
    "
    usecase VolverMenuJuego as "
    UC-0021
    Volver al menú principal
    ---
    Extensiones:
    Escoger minijuego
    "
}

/'
 ' El Usuario anónimo pude iniciar sesión y registrarse, el segundo extiende del primero.
 ' El caso de uso MandarCorreoVerificacion (Mandar correo de verificación) se incluye en registrarse.
 '/
anon --> (IniciarSesion)
(IniciarSesion) <. (Registrarse) : <<extend>>
(Registrarse) .> (MandarCorreoVerificacion) : <<include>>
sys --> (MandarCorreoVerificacion)

/'
 ' El usuario autenticado (pero no verifiado) puede ver sus datos personales desde el menú. Desde ahí
 ' puede eliminar su cuenta, verificar su correo electrónico o cerrar sesión.
 ' El caso de uso ModificarDatosPersonales (Modificar datos personales) se extiende desde ver datos personales, pero se
 ' añade la condición de que el usuario esté verificado.
 ' Además, si la modificación de datos personales es correcta, se aplica el caso de uso MandarCorreoVerificacion
 '/
userauth --> (VerDatosPersonales)
(VerDatosPersonales) <.. (EliminarCuenta) : <<extend>>
(VerDatosPersonales) <.. (CerrarSesion) : <<extend>>
(VerDatosPersonales) <. (VerificarCorreoElectronico) : <<extend>>
(VerDatosPersonales) <.. (ModificarDatosPersonales) : <<extend>>
note top of link : CONDITION {actor == Usuario verificado} 
(MandarCorreoVerificacion) <.. (ModificarDatosPersonales) : <<include>>

/'
 ' El usuario verificado puede realizar todos los casos de estadísicas y seguimiento.
 ' El caso de uso AnadirFormaFisica se extiende desde el menú de datos personales y el FiltrarEstadisticas del ConsultarEstadisticas
 '/
(VerDatosPersonales) <.. (AnadirFormaFisica) : <<extend>>
note bottom of link : CONDITION {actor == Usuario verificado} 
userverif --> (ConsultarEstadisticas)
(ConsultarEstadisticas) <. (FiltrarEstadisticas) : <<extend>>

/'
 ' El usuario verificado puede abrir el juego, desde el cual se puede activar la pantalla completa.
 ' La primera vez que se abra el juego, automáticamente se calibrará la cámara. 
 ' Después, aparecerá el menú de selección de minijuego.
 ' Desde el menú de selección de minijuego, se puede escoger el minijuego.
 ' Una vez escogido el minijuego, se puede escoger la dificultad.
 ' Una vez escogida la dificultad, se jugará el minijuego.
 ' Finalmente, se podrá ver la puntuación obtenida y volver a jugar o volver al menú principal.
 '/
userverif -> (AbrirJuego)

(AbrirJuego) <.. (Calibrar) : <<extend>>
note bottom of link : CONDITION {Solo una vez por sesión}

' Escoger minijuego después de jugar
(EscogerMinijuego) ..> (VolverMenuJuego) : <<extend>>

' Escoger minijuego después de abrir el juego
(AbrirJuego) <. (EscogerMinijuego) : <<extend>>
' Escoger dificultad después de escoger minijuego 
(EscogerMinijuego) <. (EscogerDificultad) : <<extend>>
' Escoger dificultad después de jugar 
(EscogerDificultad) ..> (VolverJugar) : <<extend>>

' Jugar minijuego globos/esquivar después de escoger dificultad
(EscogerDificultad) <. (JugarGlobos) : <<extend>>
(EscogerDificultad) <.. (JugarEsquivar) : <<extend>>
' Ver puntuaciones después de jugar minijuego globos/esquivar
(JugarGlobos) <.. (Puntuacion) : <<extend>>
(JugarEsquivar) <.. (Puntuacion) : <<extend>>
' Volver a jugar/volver al menú principal después de ver puntuaciones
(VolverMenuJuego) .> (Puntuacion) : <<extend>>
(Puntuacion) <. (VolverJugar) : <<extend>>

(AbrirJuego) <. (PantallaCompleta) : <<extend>>

@enduml