@startuml Despliegue

left to right direction
skinparam linetype ortho
skinparam RoundCorner 0

node Cliente <<Device>> {
    node "Navegador Web" <<Execution environment>> {
    }
}

node "Servidor\n(rinl.soymilk.lueng.org)" <<Device>> as Servidor {
    node "Proxy" <<Execution environment>> {
        artifact "Caddyfile" <<Artifact>> as Caddyfile
    }

    node "Docker engine" <<Execution environment>> {
        artifact "docker-compose.yml" <<Deployment spec>> as DockerCompose
        artifact ".env" <<Artifact>> as Env

        node "Frontend" <<Container>> {
            artifact "Dockerfile" <<Deployment spec>> as FrontendDockerfile

            node "Vite" <<Execution environment>> {
                artifact "App.ts" <<Artifact>> as VApp
            }
        }

        node "Backend" <<Container>> {
            artifact "Dockerfile" <<Deployment spec>> as BackendDockerfile

            node "FastAPI" <<Execution environment>> {
                artifact "app" <<Artifact>> as FApp
            }
        }

        node "Base de Datos" <<Container>> as DB {
            node "PostgreSQL" <<Execution environment>> {
                artifact "db" <<Artifact>> as Db
            }
        }

        DB -- Backend
        Backend -- Frontend
        Env ..> Backend : "<<deploy>>"
        Env ..> Frontend : "<<deploy>>"
    }
}

Cliente -- Servidor

@enduml
