@startuml ModeloDominio

skinparam linetype ortho
' skinparam class {
'     BackgroundColor #7ACFF5
' }
hide circle
skinparam classAttributeIconSize 0
skinparam roundCorner 0

package "Dominio" {
    class "Usuario" {
        - uuid: Integer
        - email: String
        - contraseña: String
        - nombre: String
        - fechaNacimiento: Date
    }

    class "Actividad" {
        - uuid: Integer
        - fecha: Date
        - minijuego: String
        - duración: Float
        - puntuación: Float
        - datos_extra: String
    }

    class "FormaFísica" {
        - uuid: Integer
        - fecha: Date
        - peso: Float
        - altura: Float
    }
}

' Un usuario puede tener muchas actividades y formas físicas
Usuario "1" --- "0..*" Actividad : Realiza >
Usuario "1" --- "0..*" FormaFísica : Registra >

' note right of Dominio
'     Los usuarios del sistema son representados por
'     la clase Usuario. Cada usuario se identifica
'     con un UUID y correo electrónico únicos.
'     Cada usuario puede registrar múltiples formas
'     físicas a lo largo del tiempo, así como
'     realizar distintas actividades.
' end note

@enduml
